//api/apiUrl.jsx
export const API = {
  LOGIN: "Login/login",
  LOGOUT: "Login/logout",
  IMPORT_CANDIDATE: "Candidate/import",
  CANDIDATE: "Candidate",
  CANDIDATE_BY_ID: "Candidate",
  SEND_NOTI: "/notifications/send",
  CHECK_NOTI: "/api/notifications/mark-as-read/",
  VIEW_NOTI_BY_USER_ID: "/api/notifications/",
  GET_EXTERNAL_CERTIFICATE_BY_ID: "ExternalCertificate/candidate",
  GET_ALL_REQUEST: "Requests",
  GET_REQUEST_BY_ID: "Requests",
  APPROVE_REQUEST: "Requests",
  REJECT_REQUEST: "Requests",
  CREATE_CANDIDATE_ACCOUNT: "User/create-from-candidate",
  GET_ALL_USER: "User",
  GET_USER_BY_ID: "User",
  UPDATE_USER: "User",
  UPDATE_PASSWORD: "User",
  FORGOT_PASSWORD: "User/forgot-password",
  RESET_PASSWORD: "User/reset-password",
};
